[phases.setup]
nixPkgs = ["python312", "pkg-config", "mysql-client"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["python manage.py collectstatic --no-input"]

[start]
cmd = "gunicorn grms_project.wsgi:application"