# Generated by Django 5.2.7 on 2026-03-15 03:59

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Examiner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=250, unique=True)),
                ('phone_no', models.CharField(max_length=15)),
                ('designation', models.CharField(max_length=50)),
                ('examiner_type', models.CharField(choices=[('Internal', 'Internal'), ('External', 'External')], max_length=20)),
                ('institution', models.CharField(max_length=100)),
                ('area_of_expertise', models.CharField(max_length=150)),
                ('availability_status', models.CharField(choices=[('Available', 'Available'), ('Not Available', 'Not Available'), ('On Leave', 'On Leave')], default='Available', max_length=20)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examiner_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('System', 'System'), ('Email', 'Email'), ('Reminder', 'Reminder'), ('Alert', 'Alert')], default='System', max_length=20)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_no', models.CharField(max_length=30, unique=True)),
                ('department', models.CharField(max_length=100)),
                ('session', models.CharField(max_length=20)),
                ('program', models.CharField(max_length=50)),
                ('enrollment_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Completed', 'Completed'), ('Withdrawn', 'Withdrawn')], default='Active', max_length=20)),
                ('admission_date', models.DateField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExtensionCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('requested_duration', models.IntegerField(help_text='Duration in days')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('supporting_document', models.FileField(blank=True, null=True, upload_to='research/extensions/')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extensions', to='accounts.student')),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('department', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=50)),
                ('availability_status', models.CharField(choices=[('Available', 'Available'), ('Not Available', 'Not Available'), ('On Leave', 'On Leave')], default='Available', max_length=20)),
                ('max_students', models.IntegerField(default=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='accounts.supervisor'),
        ),
        migrations.CreateModel(
            name='ProgressReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=20)),
                ('file', models.FileField(upload_to='research/progress_reports/')),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Under Review', 'Under Review'), ('Accepted', 'Accepted'), ('Needs Improvement', 'Needs Improvement'), ('Rejected', 'Rejected')], default='Submitted', max_length=20)),
                ('supervisor_feedback', models.TextField(blank=True, null=True)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_reports', to='accounts.student')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress_reviews', to='accounts.supervisor')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_date', models.DateTimeField()),
                ('mode', models.CharField(choices=[('Online', 'Online'), ('In-Person', 'In-Person')], max_length=20)),
                ('agenda', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('minutes_file', models.FileField(blank=True, null=True, upload_to='research/meetings/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='accounts.student')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='accounts.supervisor')),
            ],
        ),
        migrations.CreateModel(
            name='DegreeLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('verification_status', models.CharField(choices=[('Pending', 'Pending Verification'), ('Verified', 'Verified'), ('Rejected', 'Rejected'), ('Issued', 'Issued')], default='Pending', max_length=20)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('letter_file', models.FileField(blank=True, null=True, upload_to='degree_letters/')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='degree_letters', to='accounts.student')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.supervisor')),
            ],
        ),
        migrations.CreateModel(
            name='Synopsis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('document', models.FileField(upload_to='synopses/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('changes_requested', 'Changes Requested'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('review_comments', models.TextField(blank=True, null=True)),
                ('review_date', models.DateTimeField(blank=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('resubmission_deadline', models.DateField(blank=True, null=True)),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.synopsis')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_synopses', to='accounts.supervisor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synopses', to='accounts.student')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='synopses', to='accounts.supervisor')),
            ],
        ),
        migrations.CreateModel(
            name='Thesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='research/theses/')),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Under Review', 'Under Review'), ('Minor Changes Required', 'Minor Changes Required'), ('Major Changes Required', 'Major Changes Required'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Submitted', max_length=25)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('viva_result', models.CharField(blank=True, max_length=30, null=True)),
                ('final_decision_date', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theses', to='accounts.student')),
            ],
        ),
        migrations.CreateModel(
            name='ThesisEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_date', models.DateField(auto_now_add=True)),
                ('marks', models.IntegerField(blank=True, null=True)),
                ('result', models.CharField(blank=True, max_length=20, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='research/evaluation_reports/')),
                ('submitted', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('recommendation', models.CharField(blank=True, max_length=20, null=True)),
                ('examiner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.examiner')),
                ('thesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='accounts.thesis')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Student', 'Student'), ('Supervisor', 'Supervisor'), ('Admin', 'Admin'), ('Coordinator', 'Department Coordinator'), ('Examiner', 'Examiner')], default='Student', max_length=20)),
                ('phone_no', models.CharField(blank=True, max_length=15, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
