# Generated by Django 5.2.7 on 2026-06-25 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_synopsis_is_admin_uploaded_synopsis_uploaded_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='is_admin_uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='thesis',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_theses', to=settings.AUTH_USER_MODEL),
        ),
    ]
