# Generated by Django 5.2.7 on 2026-06-25 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_thesis_is_admin_uploaded_thesis_uploaded_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='degreeletter',
            name='is_admin_uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='degreeletter',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='degreeletter',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_degree_letters', to=settings.AUTH_USER_MODEL),
        ),
    ]
